### ISSUE TITLE
Lambda function returns an invalid subnet size error

### ISSUE THREAD

**Issue by jrudge-kcom** [awslabs/aws-cidr-finder#1]
Hi,

This looks like something I could really make use of but your example success template returns "An invalid subnet size was specified: 24, 25, 26". I tried some other valid combinations but nothing works.

I checked the code and subnet size check looks ok to me.  (I am not a python expert though!)

    # Check the sizes are valid
    if any(size < 16 or size > 28 for size in sizes):
        return send_response(event, context, "FAILED", reason="An invalid subnet size was specified: {}".format(", ".join(sizes)))

You may want to consider updating the role so the function can send logs to cloudwatch.

Thanks!

**Comment by stilvoid** [comment]
Thanks for the feedback, I'll put cloudwatch on the todo list for this for sure.

As for your issue, it looks like you're passing in a string containing "24, 25, 26" rather than a list of a numbers. See the example code for the correct format, e.g `Sizes: [24, 25, 26]`
