### ISSUE TITLE
Please add support for VPCs with multiple CIDR blocks

### ISSUE THREAD

**Issue by dkalintsev** [awslabs/aws-cidr-finder#3]
Please add support for VPCs that have multiple CIDR blocks associated.

Desired behaviour - when looking for an available subnet slot, keep searching through all associated CIDR blocks in order until slot is found, or the search has reached the end.

**Comment by stilvoid** [comment]
This is now in place as of 2.1.0 :)

**Comment by mody7860** [comment]
Can i use this to find contiguous blocks of CIDR's by exclusively passing a list of existing subnets CIDR ranges.  Example below
VPC CIDR Block - 10.1.0.0/16
Existing subnets [] ( a list that will be passed in as a parameter ) - 
10.1.0.0/21,
10.1.8.0/21,
10.1.16.0/21

Requested Sizes:[21,21]

Should return 10.1.24.0/21 & 10.1.32.0/21.
If so can you send a quick excerpt on the calling convention.
