### ISSUE TITLE
Not enough information to determine IP rage

### ISSUE THREAD

**Issue by bdowne01** [awslabs/aws-cidr-finder#4]
Hello guys.   Trying pretty hard to get this working on our account, and whenever I call this using a custom resource in subsequent cfn templates, we're getting this output from the Lambda Function:

```
Not enough information to determine IP range: Exception
Traceback (most recent call last):
File "/var/task/lambda.py", line 78, in lambda_handler
result = find_next_subnet(vpc_cidr, subnet_cidrs, sizes)
File "/var/task/cidr_findr.py", line 86, in find_next_subnet
attempt = Range(base=vpc.base, size=req)
File "/var/task/cidr_findr.py", line 64, in __init__
raise Exception("Not enough information to determine IP range")
Exception: Not enough information to determine IP range
```
Pretty sure we're passing everything in correctly, here's the corresponding custom resource:

```
  CidrFindr:
    Type: Custom::CidrFindr
    Properties:
      ServiceToken: !ImportValue CidrFindr
      VpcId: !Ref myVpc
      Sizes: [27,27,27]
```
For what it's worth, I also created a custom test request using the AWS console (using the CloudFormation request format) and still get the same thing.   I'm not super great at Python so really banging my head trying to understand where it's failing.

**Comment by bdowne01** [comment]
Managed to figure out where this was failing, and made some bug fixes in the code.  I'll submit these as a pull request soon.

**Comment by stilvoid** [comment]
Awesome, thanks :)

**Comment by bdowne01** [comment]
Np.  Could you add me to the repo so I can branch/pull?
