### ISSUE TITLE
Returns cidrs that are already in use. 

### ISSUE THREAD

**Issue by corrjo** [awslabs/aws-cidr-finder#6]
It worked the first time. But now when using in a new stack it returns a cidr that is either identical or within the range from the results provided to the first stack that used it.

`
The CIDR '10.10.16.0/24' conflicts with another subnet
--
`

**Comment by stilvoid** [comment]
Hmm. I can't replicate this. I wonder if you pulled the repo when there was a bug. I've added tags now and a bunch more unit tests so I'd suggest trying again with 2.0.0.

I'll close this for now but please reopen if this is still an issue :)
